### ISSUE TITLE
About Qualifications for the Final Bonus

### ISSUE THREAD

**Issue by ElliotQi** [facebookresearch/isc2021#3]
Thanks for your baseline! Here's a doubt:
The competition rules say that:
(a) to any individual, entity, or country prohibited by any applicable U.S. or non-U.S. export controls and trade sanctions; (b) to anyone on U.S. or non-U.S. government restricted parties lists; or (c) for any purpose prohibited by applicable export controls and trade sanctions, including nuclear, chemical or biological weapons, or missile technology applications without the required government authorizations. 
Could the Chinese team win the final award? What's the detailed prohibited list?

**Comment by mdouze** [comment]
I don't think China is touched by these restrictions. 
However, please confirm this with Driven Data in the forum https://community.drivendata.org/
